name: bomberos deploy
on: push
jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'  # Specify the node version you need

            - name: Install dependencies
              run: npm ci

            - name: Bundle
              run: npm run build
